# Generated by Django 3.1.4 on 2023-03-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_id', models.IntegerField()),
                ('ques', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_ques_id', models.IntegerField()),
                ('sub_ques', models.CharField(max_length=300)),
                ('ques_id', models.IntegerField()),
            ],
        ),
    ]
