# Generated by Django 3.1.4 on 2023-03-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot2', '0002_questions_sub_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('ques_id', models.IntegerField()),
                ('sub_ques_id', models.IntegerField()),
                ('answer', models.CharField(max_length=300)),
            ],
        ),
    ]
