# Generated by Django 3.1.4 on 2023-03-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot2', '0003_responses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300)),
            ],
        ),
    ]
